package com.mgdsstudio.blueberet.graphic.HUD.hudpanels;

public enum PortraitPicture {
    PlAYER_FACE, PLAYER_SPEAKING_FACE, SMARTPHONE_WITH_UNREAD_MESSAGE, SMARTPHONE_WITH_READ_MESSAGE, SMARTPHONE_WITH_BLACK_SCREEN, SMARTPHONE_WITH_SUBSCRIBER, SMARTPHONE_WITH_BLOCKED_SCREEN, SMARTPHONE_WITH_INCOMMING_CALL, NO_SUBSCRIBER, PLAYER_FACE_WITH_HALF_LIFE, PLAYER_FACE_WITH_SMALL_LIFE,PLAYER_SPEAKING_FACE_WITH_HALF_LIFE, PLAYER_SPEAKING_FACE_WITH_SMALL_LIFE, BOSS_BOAR, BOSS_BOAR_WITH_BLOOD;


}
