package com.mgdsstudio.blueberet.graphic.howtoplayanimation.girl;

interface IAnimationTypes {
    int SPRITE_INFINITY_ANIMATION_SPRITE = 0;
    int SPRITE_MOVABLE_ANIMATION_SPRITE = 1;
    int SPRITE_ANIMATION_SPRITE = 2;
    int ANIMATION_SPRITE_DISAPPEARING = 3;
    int SPRITE_THREE_SPRITES_WITH_ROTATING_SPRITE_SPRITE = 4;

    int RUN = SPRITE_INFINITY_ANIMATION_SPRITE; //added
    int GO = SPRITE_INFINITY_ANIMATION_SPRITE;  //added
    int SHOOT = SPRITE_INFINITY_ANIMATION_SPRITE;   //added
    int JUMP = SPRITE_MOVABLE_ANIMATION_SPRITE; //added aber can be remade with an animation at the end
    int AIM = SPRITE_THREE_SPRITES_WITH_ROTATING_SPRITE_SPRITE;
    int RELOAD = SPRITE_ANIMATION_SPRITE;   //added
    int KICK = SPRITE_ANIMATION_SPRITE;     //added
    int PORTAL = ANIMATION_SPRITE_DISAPPEARING; //added
    int USE_OBJECT = SPRITE_ANIMATION_SPRITE;
    int OPEN_ITEMS_LIST = SPRITE_ANIMATION_SPRITE;
    int OPEN_WEAPONS_LIST = SPRITE_ANIMATION_SPRITE;

}
